sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - sshpass
    ssh_known_hosts:
    - microserviceregistry.com
jobs:
  include:
    - if: branch = master
      script:
        - cd registry && npm run test
        - cd ../registry-ui && npm run test
        - npm run e2e
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker tag microservice-registry:1.0.0 microserviceregistry/registry:latest
        - docker tag microservice-registry-ui:1.0.0 microserviceregistry/registry-ui:latest
        - docker push microserviceregistry/registry:latest
        - docker push microserviceregistry/registry-ui:latest
    - if: branch != master
      script:
        # - cd registry && npm run test
        # - cd ../registry-ui && npm run test
        # - npm run e2e
        - echo $SSH_KEY > ssh_key
        - ssh -i ssh_key $MICROSERVICE_REGISTRY_USER@microserviceregistry.com 'echo "hello world"'
        - 


        