sudo: required
services:
  - docker
jobs:
  include:
    - if: branch = master
      script:
        - cd registry && npm run test
        - cd ../registry-ui && npm run test
        - npm run e2e
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker tag microservice-registry:1.0.0 microserviceregistry/registry:latest
        - docker tag microservice-registry-ui:1.0.0 microserviceregistry/registry-ui:latest
        - docker push microserviceregistry/registry:latest
        - docker push microserviceregistry/registry-ui:latest
    - if: branch != master
      script:
        # - cd registry && npm run test
        # - cd ../registry-ui && npm run test
        # - npm run e2e
        - eval "$(ssh-agent -s)"
        - echo "$SSH_PASS\r" | ssh-add <(echo "$SSH_KEY")
        - ssh $MICROSERVICE_REGISTRY_USER@microserviceregistry.com
        - echo "hello world"


        