version: '3'
services:
  registry:
    image: microservice-registry:1.0.0
    ports: 
      - "4000:3000"

  registry-ui:
    image: microservice-registry-ui:1.0.0
    ports: 
      - "5000:4200"
    volumes:
      - ./registry-ui/src:/app/src